### ISSUE TITLE
Unable to Submit Form Data to Onboarding Endpoint Due to  "Missing Filename Error"

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/Django-Task-Tracker#164]
When attempting to send form data to the endpoint http://localhost:8000/task-tracker/v1/user/onboarding/, I receive an error returning the message: "detail": "Missing filename. Request should include a Content-Disposition header with a filename parameter.

Expected Behavior:
It should be possible to submit the form data to the onboarding endpoint, including the optional attachment of a profile picture file.
Also form data should include fields: "photo", "birthday", "bio", "phone",  and theme of the user account.

Current Behavior:
After attempting to submit the form, I receive an error message "Missing filename", suggesting a lack of a file name in the Content-Disposition header.

**Comment by Ewa-Anna** [comment]
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/458113df-02d2-42c0-a93e-82bd314ee25e)
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/c0007ed2-bf94-44ec-bbbf-5bc49e9bd9bf)

This should be working now. 
Please note that there is no field "phone" in the model, so this will not exist.
As the field "theme" is in another model, I would suggest to just leave that in profile settings and remove that from the onboarding. Please let me know if that's fine and all is working in the updated version.
