### ISSUE TITLE
Missing "created" Field in Response Object for "/user/{id}"

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/Django-Task-Tracker#165]
Currently endpoint : "task-tracker/v1/user/users/1/" lacks "created" field in its response object.
 This field is necessary to display when the user's account was created.

![userProfile](https://github.com/Ewa-Anna/React-Django-Task-Tracker/assets/103382498/8621ebc8-91cd-4654-ac52-5a7f58722603)

**Comment by Ewa-Anna** [comment]
Added two new fields to mentioned endpoint: join_date (when the account was created) and last_loggin (when user has logged in last time).

![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/55eefbe8-1f7f-490d-abde-211b8f2eb241)

Please note that all connected endpoints (e.g. list of users) will also have this fields added.
