### ISSUE TITLE
Adding filtering functionality for projects based on tags

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/Django-Task-Tracker#177]
Currently, /task-tracker/v1/task/projects/ endpoint returns a list of all projects. To improve the usability of the API and allow users to quickly search for projects with specific tags, it is necessary to add filtering functionality for projects based on selected tags.

Requirements:

 -  Filtering should be possible by passing tags as query string parameters.
 -   Project tags can be passed multiple times as the "tags" parameter in the request. (/task-tracker/v1/task/projects/?tags=react&tags=python&tags=django)
 -  The backend should correctly parse tags from the request and return only those projects that contain at least one of the specified tags.
 -  If no tags are passed, all projects should be returned.

**Comment by Ewa-Anna** [comment]
This functionality already exists:
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/bf384bbe-b4a9-4158-b82e-606ab6583a48)
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/b034f70e-3e17-422a-ad32-bf77aeef5e75)


I am not sure if I forgot to close this issue, but either way, it's working.
