### ISSUE TITLE
Adding filtering functionality for users based on role

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/Django-Task-Tracker#178]
Currently, /task-tracker/v1/user/users/ endpoint returns a list of all users. To allow users to quickly search for users with specific roles, it is necessary to add filtering functionality for users based on selected roles.

Requirements:

- /task-tracker/v1/user/users/ endpoint should support filtering users based on roles.
- Filtering should be possible by passing a role as a query string parameter.
- User role can be passed only once as the "role" parameter in the request.
- Backend should correctly parse the role from the request and return only those users who have the specified role assigned.
    If no role is passed, all users should be returned.

**Comment by Ewa-Anna** [comment]
![image](https://github.com/Ewa-Anna/Django-Task-Tracker/assets/99288124/1e2c5aeb-5403-4aba-a2df-eecc0a6644db)

When given ?role= it will return list of users with given role.
